### ISSUE TITLE
在安装依赖时，出现如下错误，在windows和macos中都出现同样的错误

### ISSUE THREAD

**Issue by hawkmor** [Bespertrijun/PrettyServer#1]
Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      running egg_info
      writing lib/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/Users/hawkmor/Desktop/python/PrettyServer-main/myenv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/hawkmor/Desktop/python/PrettyServer-main/myenv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/hawkmor/Desktop/python/PrettyServer-main/myenv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/82/0hvfkj9s7bq682ngf_sw4rmr0000gn/T/pip-build-env-nnqkys9l/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/82/0hvfkj9s7bq682ngf_sw4rmr0000gn/T/pip-build-env-nnqkys9l/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/82/0hvfkj9s7bq682ngf_sw4rmr0000gn/T/pip-build-env-nnqkys9l/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 288, in <module>
        File "/private/var/folders/82/0hvfkj9s7bq682ngf_sw4rmr0000gn/T/pip-build-env-nnqkys9l/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/82/0hvfkj9s7bq682ngf_sw4rmr0000gn/T/pip-build-env-nnqkys9l/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/82/0hvfkj9s7bq682ngf_sw4rmr0000gn/T/pip-build-env-nnqkys9l/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/private/var/folders/82/0hvfkj9s7bq682ngf_sw4rmr0000gn/T/pip-build-env-nnqkys9l/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/82/0hvfkj9s7bq682ngf_sw4rmr0000gn/T/pip-build-env-nnqkys9l/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/private/var/folders/82/0hvfkj9s7bq682ngf_sw4rmr0000gn/T/pip-build-env-nnqkys9l/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/82/0hvfkj9s7bq682ngf_sw4rmr0000gn/T/pip-build-env-nnqkys9l/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 321, in run
          self.find_sources()
        File "/private/var/folders/82/0hvfkj9s7bq682ngf_sw4rmr0000gn/T/pip-build-env-nnqkys9l/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 329, in find_sources
          mm.run()
        File "/private/var/folders/82/0hvfkj9s7bq682ngf_sw4rmr0000gn/T/pip-build-env-nnqkys9l/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 551, in run
          self.add_defaults()
        File "/private/var/folders/82/0hvfkj9s7bq682ngf_sw4rmr0000gn/T/pip-build-env-nnqkys9l/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
          sdist.add_defaults(self)
        File "/private/var/folders/82/0hvfkj9s7bq682ngf_sw4rmr0000gn/T/pip-build-env-nnqkys9l/overlay/lib/python3.12/site-packages/setuptools/command/sdist.py", line 112, in add_defaults
          super().add_defaults()
        File "/private/var/folders/82/0hvfkj9s7bq682ngf_sw4rmr0000gn/T/pip-build-env-nnqkys9l/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/private/var/folders/82/0hvfkj9s7bq682ngf_sw4rmr0000gn/T/pip-build-env-nnqkys9l/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<string>", line 204, in get_source_files
        File "/private/var/folders/82/0hvfkj9s7bq682ngf_sw4rmr0000gn/T/pip-build-env-nnqkys9l/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
======================================================================
其中在安装之前提示过，opencc的服务最新版本为0.2版本，而依赖中为1.1.1
ERROR: Could not find a version that satisfies the requirement OpenCC==1.1.1 (from versions: 0.1, 0.2)
ERROR: No matching distribution found for OpenCC==1.1.1
报了这个错误

**Comment by Bespertrijun** [comment]
可以尝试这样解决问题 [pip install --upgrade opencc](https://github.com/Bespertrijun/PrettyServer?tab=readme-ov-file#5-%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9).

**Comment by hawkmor** [comment]
并不管用，只能下载到 0.2.0 版本的😓

**Comment by Bespertrijun** [comment]
哦，这是arm的原因，可以手动build，这是linux的命令，win和mac应该也差不多，可以试试看
wget https://github.com/BYVoid/OpenCC/archive/refs/tags/ver.1.1.1.tar.gz &&
tar -xzf ver.1.1.1.tar.gz &&
cd ./OpenCC-ver.1.1.1/python &&
pip install -q wheel &&
apt-get install -y cmake &&
python setup.py bdist_wheel &&
cd ./dist &&
pip install ./OpenCC-ver.1.1.1/python/dist/OpenCC-1.1.1-py3-none-manylinux1_aarch64.whl
#若报错：OpenCC-1.1.1-py3-none-manylinux1_aarch64.whl is not a supported wheel on this platform.
尝试：
mv OpenCC-1.1.1-py3-none-manylinux1_aarch64.whl OpenCC-1.1.1-py3-none-linux_aarch64.whl &&
pip install ./OpenCC-1.1.1-py3-none-linux_aarch64.whl
