### ISSUE TITLE
同步报错，大佬能看看是怎么回事么？

### ISSUE THREAD

**Issue by CookieJaySJ** [Bespertrijun/PrettyServer#12]
这个是日志：
ps  | 2024-06-17 17:07:27.466 | INFO     | __main__:main:35 - 初始化中.....
ps  | 2024-06-17 17:07:27.499 | INFO     | __main__:main:46 - Taks 初始化同步参数
ps  | 2024-06-17 17:07:27.499 | INFO     | task.synctask:cronsync:446 - Plex(plex1) / Emby(emby1)：开始同步进度
ps  | 2024-06-17 17:07:27.723 | CRITICAL | task.synctask:cronsync:557 - Plex(plex1) / Emby(emby1)同步进度失败 ：
ps  |  Traceback (most recent call last):
ps  |   File "/home/PrettyServer/task/synctask.py", line 451, in cronsync
ps  |     server2_history = await server2.history()
ps  |                       ^^^^^^^^^^^^^^^^^^^^^^^
ps  |   File "/home/PrettyServer/server/embyserver.py", line 141, in history
ps  |     media.LastPlayedDate = datetime.fromisoformat(
ps  |     ^^^^^
ps  | UnboundLocalError: cannot access local variable 'media' where it is not associated with a value
ps  | 
ps  | 2024-06-17 17:07:28.190 | INFO     | __main__:main:50 - 启动完成，开始调度任务

**Comment by Bespertrijun** [comment]
看着像是同步的媒体类型不是电影或者单集吧，同步的啥？音乐？看看播放历史

**Comment by CookieJaySJ** [comment]
> 看着像是同步的媒体类型不是电影或者单集吧，同步的啥？音乐？看看播放历史

plex有个音乐库，除了这个库以外，其他库的名字都对应
