### ISSUE TITLE
plex电视剧单集下面的演员没有中文化

### ISSUE THREAD

**Issue by jiezaizone** [Bespertrijun/PrettyServer#5]
<img width="1130" alt="image" src="https://github.com/Bespertrijun/PrettyServer/assets/28976666/80dcbe55-e810-468a-8522-bb28bd49ac6e">
<img width="1169" alt="image" src="https://github.com/Bespertrijun/PrettyServer/assets/28976666/0b7ec4c0-c6d6-434a-995f-7397d2319b9d">

如截图所示，plex电视剧剧情下面的演员是有中文化的，点进去到单集下面的演员名单就没有中文化了，如果能够一起加上中文化就再好不过了

**Comment by Juhraya** [comment]
请教一下配置，我的plex任何界面都无法汉化。

**Comment by jiezaizone** [comment]
> 请教一下配置，我的plex任何界面都无法汉化。

脚本是定时运行的，要到运行时间才会执行的，看看日志，先确认一下脚本有没有运行

**Comment by jiezaizone** [comment]
> 请教一下配置，我的plex任何界面都无法汉化。

Server:
    # 随意填，给你的plex起个名字，不要重复
  - name: plex1
    # 媒体服务器类型，plex 还是 emby
    type: plex
    url: http://127.0.0.1:32400
    token: xxxxxxxxxxxxxxxxx
    # 替换为中文演员
    roletask: 
      # 是否运行 注意大小写
      run: False
      #crontab表达式
      crontab: '0 6 * * *'
    # 调整标题排序规则 + 拼音搜索
    sorttask: 
      run: True
      crontab: '0 6 * * *'
    # 定时刷新指定库
    scantask:
      run: False
      library: 
      #格式 - 库名: crontab表达式 
        - 新番: '* * * * *'
        - 电影: '* * * * *'
        - 啦啦啦: '* * * * *'

按照配置项的说明，填写你的配置

**Comment by Juhraya** [comment]
感谢解答，我也是按照上述格式设置的，并且映射了log文件夹和config.yaml文件，映射如下：
-v /data/prettyserver/config.yaml:/home/config.yaml -v /data/prettyserver/log:/log

进入容器内有log如下：
Traceback (most recent call last):
  File "/home/PrettyServer/conf/conf.py", line 7, in check_exist
    result = dict[key]
             ~~~~^^^^^
KeyError: 'Synctask'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/PrettyServer/conf/conf.py", line 27, in <module>
    SYNC_TASK_LIST = check_exist(data ,'Synctask','conf')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/PrettyServer/conf/conf.py", line 10, in check_exist
    raise ConfigError(f'{title}缺失{key}: 请检查config.yaml文件')
util.exception.ConfigError: conf缺失Synctask: 请检查config.yaml文件
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/./PrettyServer/main.py", line 6, in <module>
    from server.server import get_server
  File "/home/PrettyServer/server/server.py", line 2, in <module>
    from server.plexserver import Plexserver
  File "/home/PrettyServer/server/plexserver.py", line 6, in <module>
    from util.util import Util
  File "/home/PrettyServer/util/util.py", line 7, in <module>
    from conf.conf import TMDB_API,PROXY,ISPROXY
  File "/home/PrettyServer/conf/conf.py", line 29, in <module>
    raise ConfigError('请检查config.yaml文件')
util.exception.ConfigError: 请检查config.yaml文件
Traceback (most recent call last):
  File "/home/PrettyServer/conf/conf.py", line 7, in check_exist
    result = dict[key]
             ~~~~^^^^^
KeyError: 'Synctask'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/PrettyServer/conf/conf.py", line 27, in <module>
    SYNC_TASK_LIST = check_exist(data ,'Synctask','conf')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/PrettyServer/conf/conf.py", line 10, in check_exist
    raise ConfigError(f'{title}缺失{key}: 请检查config.yaml文件')
util.exception.ConfigError: conf缺失Synctask: 请检查config.yaml文件
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/./PrettyServer/main.py", line 6, in <module>
    from server.server import get_server
  File "/home/PrettyServer/server/server.py", line 2, in <module>
    from server.plexserver import Plexserver
  File "/home/PrettyServer/server/plexserver.py", line 6, in <module>
    from util.util import Util
  File "/home/PrettyServer/util/util.py", line 7, in <module>
    from conf.conf import TMDB_API,PROXY,ISPROXY
  File "/home/PrettyServer/conf/conf.py", line 29, in <module>
    raise ConfigError('请检查config.yaml文件')
util.exception.ConfigError: 请检查config.yaml文件

但是在映射的/data/prettyserver/log目录下是空的。

config.yaml配置如下：
Server:
    # 随意填，给你的plex起个名字，不要重复
  - name: mynas
    # 媒体服务器类型，plex 还是 emby
    type: plex
    url: http://127.0.0.1:32400
    token: ********************
    # 替换为中文演员
    roletask: 
      # 是否运行 注意大小写
      run: True
      #crontab表达式
      crontab: '30 21 * * *'
    # 调整标题排序规则 + 拼音搜索
    sorttask: 
      run: True
      crontab: '0 6 * * *'
    scantask:
      run: False
      library: 
      #格式 - 库名: crontab表达式 
        - 亲子电影: '* 6 * * *'
  

Env:
  # Tmdb API (中文演员，emby季标题需要)
  tmdb_api: *******************************
  # 协程并发数，越大越快，越吃系统资源
  concurrent_num: 1000
  # 日志存放路径，默认运行文件夹
  log_path: default
  # 日志记录等级：DEBUG,INFO,WARNING,ERROR
  log_level: INFO
  # 日志保留天数
  log_expire: 3
  # 仅访问tmdb代理(更换tmdb api，目前国内能访问)
  proxy:
    # 是否启用代理
    isproxy: False
    # 只支持http代理
    http: "http://127.0.0.1:7890"
